name: devil_scout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  crypto: ^3.0.6
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_sign_in: ^6.2.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.3
  supabase_flutter: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
  - family: Noto Sans
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf
      - asset: assets/fonts/NotoSans-Bold.ttf
        weight: 700
