name: Build
on: [push]
permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Download dependencies
        run: flutter pub get
      - name: Generate source files
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v3
        with:
          fail-on-warnings: true
          fail-on-infos: true
