name: Build
on: [push]
permissions:
  contents: read

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Download dart dependencies
        run: flutter pub get
      - name: Generate source files
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build for iOS
        run: flutter build ios --release --no-codesign

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Download dart dependencies
        run: flutter pub get
      - name: Generate source files
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build for Android
        run: flutter build appbundle --release
